version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
        MAVEN_OPTS: ~XmX3200m
    steps:
    - restore_cache:
        - v1-dependencies-({checksum "pom.xml"})
        - v1-dependencies-
    - run: mvn: dependency:go-offline
    - save_cache:
        paths:
          - ~/.m2
        key: v1-dependencies-({checksum "pom.xml"})
  test:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - run: mvn install

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
    - build
    - test
