version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
        MAVEN_OPTS: ~XmX3200m
    steps:
    - checkout
    - run: mvn dependency:go-offline
  test:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - run: mvn install

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
    - build
    - test
